name: Buildpack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-login
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: build
      uses: crswty/buildpack-action@master
      env:
        IMAGE_NAME: crswty/spring-music:latest
        VARS: app=dev
    - name: docker-push
      run: docker push crswty/spring-music:latest
