name: Buildpack
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker-login
      env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: build
      uses: kdihalas/buildpack-action@master
      env:
        IMAGE_NAME: kdihalas/knative-nodejs-example:latest
        BUILDER: cloudfoundry/cnb:bionic
        CONTEXT: nodejs
        VARS: app=dev
    - name: docker-push
      run: docker push kdihalas/knative-nodejs-example:latest
